### PR TITLE
cucumber-parent: multi-release jar for jpms

### PR DESCRIPTION
**Pull request by nhojpatrick**
I've been working with this pom setup for about a month now. I've got cucumber-expressions, datatable, gherkin and tag-expressions branches all building with it dual support java 1.8 and 11 jars, and cucumber-jvm:5.0.0-SNAPSHOT depending upon those versions. I don't believe I'll need to change this pom to fix any build or test issues with downstream modules so want to release this so i can move on with cucumber jpms.

Some version properties have changes and so has some encoding values.

Things like ModuleInfoHack have been needed when created shaded/bundles of dependencies so the compiler doesn't fail the build as that pom doesn't contain any packages as described in modules-info.java.

### CODE REVIEW

**Comment by nhojpatrick** [comment]
Travis needs updating so toolchain has access to java 1.8 and java 11.

So for my mac I have the following toolchains.xml but not sure how to dynamically/statically create the same for travis.

```
$ cat ~/.m2/toolchains.xml 
<?xml version="1.0" encoding="UTF-8"?>
<toolchains xmlns="http://maven.apache.org/TOOLCHAINS/1.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/TOOLCHAINS/1.1.0 http://maven.apache.org/xsd/toolchains-1.1.0.xsd">
	<toolchain>
		<type>jdk</type>
		<provides>
			<version>1.8</version>
			<vendor>openjdk</vendor>
			<id>openjdk-1.8</id>
		</provides>
		<configuration>
			<jdkHome>/Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home</jdkHome>
		</configuration>
	</toolchain>
	<toolchain>
		<type>jdk</type>
		<provides>
			<version>11</version>
			<vendor>openjdk</vendor>
			<id>openjdk-11</id>
		</provides>
		<configuration>
			<jdkHome>/Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home</jdkHome>
		</configuration>
	</toolchain>
</toolchains>
$
```

**Comment by mpkorstanje** [comment]
I think we'll have to do the migration to circle CI and start building in a docker image. Either that or jump straight to java 11 and compile down to 8 again.

**Comment by mpkorstanje** [comment]
For everything else. I haven't had a chance to look into the build tooling for Java 11 yet. I probebly won't get round to it until after v5 is released and may a bit later until all the immediate bugs are solved.

However that shouldn't stop you. 
 - If you are going to make a docker image you can include the tool-chain.xml
 - If you are going to use travis, I reckon you can provide the location of the tool-chain.xml via a CLI option.

However If we use a single JDK to build everything that shouldn't be needed I think.

**Comment by mpkorstanje** [comment]
> Things like ModuleInfoHack have been needed when created shaded/bundles of dependencies so the compiler doesn't fail the build as that pom doesn't contain any packages as described in modules-info.java.

I understand what it does, but could you include an explanation in a comment. 

Also which shaded dependencies do we still have? Ideally we do not export them via `module-info.java` in the first place. It's a bit waste full I'd rather shade them multiple times and preferably directly into the module that uses them rather then via a `x-deps` dependency.

**Comment by mpkorstanje** [comment]
Okay. That might be a problem w.r.t. Apache dependencies. Then we'd end up with a rather complicated license on our jars

**Comment by mpkorstanje** [comment]
https://github.com/cucumber/cucumber-jvm/issues/1793 should take care of the hack.

**Comment by mpkorstanje** [comment]
I'm just going to wait for Maven to catch up. It's too much of a pain right now to get it right.

**Pull request closed without merging**
